### ISSUE TITLE
Add support for gpt4-x-alpaca

### ISSUE THREAD

**Issue by priamai** [jmorganca/ollama#1361]
Hi there,
this is an amazing model:
https://huggingface.co/chavinlo/gpt4-x-alpaca
Cheers.

**Comment by technovangelist** [comment]
This model appears to be no longer supported by llamacpp: 

```
matt@matt:~/llama.cpp$ python3 convert.py ~/chavinlo_gpt4-x-alpaca
Loading model file /home/matt/chavinlo_gpt4-x-alpaca/pytorch_model-00001-of-00006.bin
Loading model file /home/matt/chavinlo_gpt4-x-alpaca/pytorch_model-00001-of-00006.bin
Loading model file /home/matt/chavinlo_gpt4-x-alpaca/pytorch_model-00002-of-00006.bin
Loading model file /home/matt/chavinlo_gpt4-x-alpaca/pytorch_model-00003-of-00006.bin
Loading model file /home/matt/chavinlo_gpt4-x-alpaca/pytorch_model-00004-of-00006.bin
Loading model file /home/matt/chavinlo_gpt4-x-alpaca/pytorch_model-00005-of-00006.bin
Loading model file /home/matt/chavinlo_gpt4-x-alpaca/pytorch_model-00006-of-00006.bin
params = Params(n_vocab=32001, n_embd=5120, n_layer=40, n_ctx=2048, n_ff=13824, n_head=40, n_head_kv=40, n_experts=None, n_experts_used=None, f_norm_eps=1e-06, rope_scaling_type=None, f_rope_freq_base=None, f_rope_scale=None, n_orig_ctx=None, rope_finetuned=None, ftype=None, path_model=PosixPath('/home/matt/chavinlo_gpt4-x-alpaca'))
None of PyTorch, TensorFlow >= 2.0, or Flax have been found. Models won't be available and only tokenizers, configuration and file/data utilities can be used.
You are using the default legacy behaviour of the <class 'transformers.models.llama.tokenization_llama.LlamaTokenizer'>. This is expected, and simply means that the `legacy` (previous) behavior will be used so nothing changes for you. If you want to use the new behaviour, set `legacy=False`. This should only be set if you understand what it means, and thoroughly read the reason why this was added as explained in https://github.com/huggingface/transformers/pull/24565
32000 32000
Vocab info: <VocabLoader with 32000 base tokens and 1 added tokens>
Traceback (most recent call last):
  File "/home/matt/llama.cpp/convert.py", line 1279, in <module>
    main()
  File "/home/matt/llama.cpp/convert.py", line 1259, in main
    special_vocab = gguf.SpecialVocab(model_plus.paths[0].parent,
  File "/home/matt/llama.cpp/gguf-py/gguf/vocab.py", line 33, in __init__
    self._load(Path(path))
  File "/home/matt/llama.cpp/gguf-py/gguf/vocab.py", line 79, in _load
    self._try_load_from_config_json(path)
  File "/home/matt/llama.cpp/gguf-py/gguf/vocab.py", line 184, in _try_load_from_config_json
    self._set_special_token(typ, config.get(f'{typ}_token_id'))
  File "/home/matt/llama.cpp/gguf-py/gguf/vocab.py", line 115, in _set_special_token
    raise ValueError(f'invalid value for special token type {typ}: {tid}')
ValueError: invalid value for special token type pad: -1
```

**Comment by dhiltgen** [comment]
This model architecture is now supported. For example `ollama run hf.co/mradermacher/gpt4-x-alpaca-GGUF:Q4_K_M`
