### ISSUE TITLE
Langchain python rag doc example Mac only

### ISSUE THREAD

**Issue by technovangelist** [jmorganca/ollama#924]
The example requires a Mac only package but I think that's not actually the case.

**Comment by SoloBSD** [comment]
This is on Linux Mint (latest)

====
python3 main.py
/home/memo/.local/lib/python3.10/site-packages/langchain/__init__.py:34: UserWarning: Importing PromptTemplate from langchain root module is no longer supported. Please use langchain.prompts.PromptTemplate instead.
  warnings.warn(
Traceback (most recent call last):
  File "/home/memo/Projects/ollama/examples/langchain-python-rag-document/main.py", line 26, in <module>
    data = loader.load()
  File "/home/memo/.local/lib/python3.10/site-packages/langchain/document_loaders/pdf.py", line 134, in load
    return loader.load()
  File "/home/memo/.local/lib/python3.10/site-packages/langchain/document_loaders/unstructured.py", line 86, in load
    elements = self._get_elements()
  File "/home/memo/.local/lib/python3.10/site-packages/langchain/document_loaders/pdf.py", line 57, in _get_elements
    from unstructured.partition.pdf import partition_pdf
  File "/home/memo/.local/lib/python3.10/site-packages/unstructured/partition/pdf.py", line 24, in <module>
    from pdfminer.utils import open_filename
ImportError: cannot import name 'open_filename' from 'pdfminer.utils' (/home/memo/.local/lib/python3.10/site-packages/pdfminer/utils.py)

**Comment by SoloBSD** [comment]
I think it is fixed now:
- Uninstalled pdfminer and installed pdfminer.six
