### ISSUE TITLE
Langchain privategpt example use deprecated code

### ISSUE THREAD

**Issue by technovangelist** [jmorganca/ollama#928]
It's broken and gives an error about deprecated chroma code

**Comment by SoloBSD** [comment]
This is on Linux Mint (latest)
======

python ingest.py 
Creating new vectorstore
Loading documents from source_documents
Loading new documents: 100%|██████████████████████| 1/1 [00:00<00:00,  3.04it/s]
Loaded 169 new documents from source_documents
Split into 1101 chunks of text (max. 500 tokens each)
Creating embeddings. May take some minutes...
Traceback (most recent call last):
  File "/home/memo/Projects/ollama/examples/langchain-python-rag-privategpt/ingest.py", line 161, in <module>
    main()
  File "/home/memo/Projects/ollama/examples/langchain-python-rag-privategpt/ingest.py", line 153, in main
    db = Chroma.from_documents(texts, embeddings, persist_directory=persist_directory, client_settings=CHROMA_SETTINGS)
  File "/home/memo/Projects/ollama/examples/langchain-python-rag-privategpt/.venv/lib/python3.10/site-packages/langchain/vectorstores/chroma.py", line 603, in from_documents
    return cls.from_texts(
  File "/home/memo/Projects/ollama/examples/langchain-python-rag-privategpt/.venv/lib/python3.10/site-packages/langchain/vectorstores/chroma.py", line 558, in from_texts
    chroma_collection = cls(
  File "/home/memo/Projects/ollama/examples/langchain-python-rag-privategpt/.venv/lib/python3.10/site-packages/langchain/vectorstores/chroma.py", line 120, in __init__
    self._client = chromadb.Client(_client_settings)
  File "/home/memo/Projects/ollama/examples/langchain-python-rag-privategpt/.venv/lib/python3.10/site-packages/chromadb/__init__.py", line 190, in Client
    return ClientCreator(tenant=tenant, database=database, settings=settings)
  File "/home/memo/Projects/ollama/examples/langchain-python-rag-privategpt/.venv/lib/python3.10/site-packages/chromadb/api/client.py", line 133, in __init__
    super().__init__(settings=settings)
  File "/home/memo/Projects/ollama/examples/langchain-python-rag-privategpt/.venv/lib/python3.10/site-packages/chromadb/api/client.py", line 36, in __init__
    SharedSystemClient._create_system_if_not_exists(self._identifier, settings)
  File "/home/memo/Projects/ollama/examples/langchain-python-rag-privategpt/.venv/lib/python3.10/site-packages/chromadb/api/client.py", line 43, in _create_system_if_not_exists
    new_system = System(settings)
  File "/home/memo/Projects/ollama/examples/langchain-python-rag-privategpt/.venv/lib/python3.10/site-packages/chromadb/config.py", line 267, in __init__
    if settings[key] is not None:
  File "/home/memo/Projects/ollama/examples/langchain-python-rag-privategpt/.venv/lib/python3.10/site-packages/chromadb/config.py", line 204, in __getitem__
    raise ValueError(LEGACY_ERROR)
ValueError: You are using a deprecated configuration of Chroma.

If you do not have data you wish to migrate, you only need to change how you construct
your Chroma client. Please see the "New Clients" section of https://docs.trychroma.com/migration.
________________________________________________________________________________________________

If you do have data you wish to migrate, we have a migration tool you can use in order to
migrate your data to the new Chroma architecture.
Please `pip install chroma-migrate` and run `chroma-migrate` to migrate your data and then
change how you construct your Chroma client.

See https://docs.trychroma.com/migration for more information or join our discord at https://discord.gg/8g5FESbj for help!
